export const envConfig = {
    // 应用名称
    APP_NAME: process.env.APP_NAME,
    // 加密盐
    MD5_SALT: process.env.MD5_SALT,
    // 监听端口
    APP_PORT: Number(process.env.APP_PORT),
    // 监听主机
    LISTEN_HOST: process.env.LISTEN_HOST,
    // 超级管理员密码
    DEV_PASSWORD: process.env.DEV_PASSWORD,
    // 请求体大小 10M
    BODY_LIMIT: Number(process.env.BODY_LIMIT),
    // 是否进行参数验证
    PARAMS_CHECK: process.env.PARAMS_CHECK,
    // 数据库表主键方案
    TABLE_PRIMARY_KEY: process.env.TABLE_PRIMARY_KEY,
    // 时区
    TIMEZONE: process.env.TIMEZONE,
    // 数据库配置
    MYSQL_HOST: process.env.MYSQL_HOST,
    MYSQL_PORT: Number(process.env.MYSQL_PORT),
    MYSQL_DB: process.env.MYSQL_DB,
    MYSQL_USERNAME: process.env.MYSQL_USERNAME,
    MYSQL_PASSWORD: process.env.MYSQL_PASSWORD,
    // Redis配置
    REDIS_HOST: process.env.REDIS_HOST,
    REDIS_PORT: Number(process.env.REDIS_PORT),
    REDIS_USERNAME: process.env.REDIS_USERNAME,
    REDIS_PASSWORD: process.env.REDIS_PASSWORD,
    REDIS_DB: Number(process.env.REDIS_DB),
    REDIS_KEY_PREFIX: process.env.REDIS_KEY_PREFIX,
    // JWT配置
    JWT_SECRET: process.env.JWT_SECRET,
    JWT_EXPIRES_IN: process.env.JWT_EXPIRES_IN,
    JWT_ALGORITHM: process.env.JWT_ALGORITHM,
    // 邮件配置
    MAIL_HOST: process.env.MAIL_HOST,
    MAIL_PORT: Number(process.env.MAIL_PORT),
    MAIL_POOL: process.env.MAIL_POOL,
    MAIL_SECURE: process.env.MAIL_SECURE,
    MAIL_USER: process.env.MAIL_USER,
    MAIL_PASS: process.env.MAIL_PASS,
    MAIL_SENDER: process.env.MAIL_SENDER,
    MAIL_ADDRESS: process.env.MAIL_ADDRESS
};
