export const envConfig = {
    // 应用名称
    APP_NAME: Bun.env.APP_NAME,
    // 加密盐
    MD5_SALT: Bun.env.MD5_SALT,
    // 监听端口
    APP_PORT: Number(Bun.env.APP_PORT),
    // 监听主机
    LISTEN_HOST: Bun.env.LISTEN_HOST,
    // 超级管理员密码
    DEV_PASSWORD: Bun.env.DEV_PASSWORD,
    // 请求体大小 10M
    BODY_LIMIT: Number(Bun.env.BODY_LIMIT),
    // 是否进行参数验证
    PARAMS_CHECK: Bun.env.PARAMS_CHECK,
    // 是否显示接口文档
    SWAGGER: Bun.env.SWAGGER,
    // 数据库表主键方案
    TABLE_PRIMARY_KEY: Bun.env.TABLE_PRIMARY_KEY,
    // 时区
    TIMEZONE: Bun.env.TIMEZONE,
    // 数据库配置
    MYSQL_HOST: Bun.env.MYSQL_HOST,
    MYSQL_PORT: Number(Bun.env.MYSQL_PORT),
    MYSQL_DB: Bun.env.MYSQL_DB,
    MYSQL_USERNAME: Bun.env.MYSQL_USERNAME,
    MYSQL_PASSWORD: Bun.env.MYSQL_PASSWORD,
    // Redis配置
    REDIS_HOST: Bun.env.REDIS_HOST,
    REDIS_PORT: Number(Bun.env.REDIS_PORT),
    REDIS_USERNAME: Bun.env.REDIS_USERNAME,
    REDIS_PASSWORD: Bun.env.REDIS_PASSWORD,
    REDIS_DB: Number(Bun.env.REDIS_DB),
    REDIS_KEY_PREFIX: Bun.env.REDIS_KEY_PREFIX,
    // JWT配置
    JWT_SECRET: Bun.env.JWT_SECRET,
    JWT_EXPIRES_IN: Bun.env.JWT_EXPIRES_IN,
    JWT_ALGORITHM: Bun.env.JWT_ALGORITHM,
    // 邮件配置
    MAIL_HOST: Bun.env.MAIL_HOST,
    MAIL_PORT: Number(Bun.env.MAIL_PORT),
    MAIL_POOL: Bun.env.MAIL_POOL,
    MAIL_SECURE: Bun.env.MAIL_SECURE,
    MAIL_USER: Bun.env.MAIL_USER,
    MAIL_PASS: Bun.env.MAIL_PASS,
    MAIL_SENDER: Bun.env.MAIL_SENDER,
    MAIL_ADDRESS: Bun.env.MAIL_ADDRESS
};
