# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Node.js Package

on:
    push:
        tags:
            - 'v*'

jobs:
    publish:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
              with:
                  fetch-depth: 1

            - name: Setup Node
              uses: actions/setup-node@v4
              with:
                  node-version: 20

            - name: Setup Pnpm
              uses: pnpm/action-setup@v4
              with:
                  version: latest
                  run_install: true

            - name: Authenticate with Registry
              run: |
                echo "link-workspace-packages=true" > ./.npmrc
                echo "//registry.npmjs.org/:_authToken=${{ secrets.npm_token }}" >> ./.npmrc
                npm whoami

            - name: Publish to npm
              run: pnpm run r

